# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Based on Ubuntu 16.04
  config.vm.box = "ubuntu/xenial32"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true
    # Customize VirtualBox machine
    vb.memory = "1024"
    vb.customize ["modifyvm", :id, "--vram", "64", "--accelerate3d", "on", "--clipboard", "bidirectional"]
    vb.customize ["modifyvm", :id, "--uartmode1", "disconnected" ]
  end

  config.vm.provision "setup", type: "shell", path: "provision/setup.sh"
  config.vm.provision "dotfiles", type: "shell", privileged: false,
    inline: "rsync -r -u -i -h /vagrant/provision/dotfiles/ $HOME"
  config.vm.provision "build", type: "shell", privileged: false, path: "provision/build.sh"

  # Customized
  config.vm.synced_folder "../", "/opt/disk/src/iptvdream"
  config.vm.provision "make-links", type: "shell", privileged: false, inline: <<-SHELL
    ln -sf -v "/opt/disk/src/iptvdream/src" "/opt/disk/usr/lib/enigma2/python/Plugins/Extensions/IPtvDream"
    ln -sf -v "/opt/disk/src/iptvdream/skin" "/opt/disk/usr/share/enigma2/IPtvDream"
  SHELL

end
